config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    get :following, on: :member
    get :followers, on: :member
  end

  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, data: { turbo: false } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field my-3">
    <%= f.text_area :content, placeholder: "Compose new micropost...", class:"form-control"%>
  </div>
  <span>
    <%= f.file_field :picture %>
  </span>
  <p class="mt-3">
  <%= f.submit "Post", class: "btn btn-primary px-5" %>
  </p>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>" class="btn btn-info">
    <strong id="following" class="">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>" class="btn btn-dark">
    <strong id="followers" class="">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class="mt-3" style="font-size:2.0rem">
  <%= link_to gravatar_for(current_user, size: 60), current_user %>
  <%= current_user.name %>
</div>
<div class="mx-5">
<span><%= link_to "view my profile", current_user %></span>
<p><%= pluralize(current_user.microposts.count, "micropost") %></p>
</div>