config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    get :following, on: :member
    get :followers, on: :member
  end

  resources :account_activations, only: %i[edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<div class="container p-4"></div>
<footer class="fixed-bottom bg-light text-center">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <div class='navbar navbar-expand navbar-light justify-content-center'>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path, class: 'btn btn-light' %></li>
        <li><%= link_to "Contact", contact_path, class: 'btn btn-light' %></li>
        <li><a href="http://news.railstutorial.org/", class='btn btn-light'>News</a></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-expand navbar-light bg-light">
  <div class="container justify-content-start">
    <h4>
      <%= link_to "Sample app", root_path, class: 'navbar-brand text-primary' %>
    </h4>
    <ul class="nav justify-content-end">
      <li><%= link_to "Home", root_path, class: 'btn btn-light' %></li>
      <li><%= link_to "Help", help_path, class: 'btn btn-light' %></li>
      <% if logged_in? %>
        <li><%= link_to "Users", users_path, class: 'btn btn-light' %></li>
        <div class="nav-item dropdown">
          <a class="text-dark nav-link dropdown-toggle" href="#" id="navbarDropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li class="dropdown-item"><%= button_to "Profile", current_user, method: "get",
                                                    class: 'text-decoration-none btn btn-link text-dark' %></li>
            <li class="dropdown-item"><%= button_to "Settings", edit_user_path(current_user), method: "get",
                                                    class: 'text-decoration-none btn btn-link text-dark' %></li>
            <li class="dropdown-item"><%= button_to "Log out", logout_path, method: "delete",
                                                    class: 'text-decoration-none btn btn-link text-dark' %></li>
          </ul>
        </div>
      <% else %>
        <li><%= link_to "Log in", login_path, class: 'btn btn-light' %></li>
      <% end %>
    </ul>
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body class="mb-5">
<%= render 'layouts/header' %>
<div class="container">
  <%= bootstrap_flash %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>